# Generated by Django 6.0.3 on 2026-03-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=20, unique=True)),
                ('marka_model', models.CharField(max_length=100)),
                ('kapasite', models.PositiveIntegerField(default=4)),
                ('aktif_mi', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=150)),
                ('telefon', models.CharField(max_length=20)),
                ('aktif_mi', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_turu', models.CharField(choices=[('gidis', 'Gidiş'), ('donus', 'Dönüş'), ('gidis_donus', 'Gidiş-Dönüş')], max_length=50)),
                ('transfer_durumu', models.CharField(choices=[('beklemede', 'Beklemede'), ('yolda', 'Yolda'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='beklemede', max_length=50)),
                ('musteri_adi', models.CharField(max_length=150)),
                ('musteri_kodu', models.CharField(blank=True, max_length=50, null=True)),
                ('musteri_telefon', models.CharField(max_length=20)),
                ('musteri_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('varis_yer_turu', models.CharField(choices=[('havalimani', 'Havalimanı'), ('gar', 'Gar'), ('kamu', 'Kamu'), ('diger', 'Diğer')], max_length=50)),
                ('sefer_no', models.CharField(blank=True, max_length=100, null=True)),
                ('alis_yeri', models.CharField(max_length=255)),
                ('alis_saati', models.DateTimeField()),
                ('varis_yeri', models.CharField(max_length=255)),
                ('varis_saati', models.DateTimeField(blank=True, null=True)),
                ('kisi_sayisi', models.PositiveIntegerField(default=1)),
                ('cocuk_sayisi', models.PositiveIntegerField(default=0)),
                ('bebek_sayisi', models.PositiveIntegerField(default=0)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odeme_turu', models.CharField(choices=[('nakit', 'Nakit'), ('kredi_karti', 'Kredi Kartı'), ('havale', 'Havale/EFT')], max_length=50)),
                ('faturalama_durumu', models.BooleanField(default=False)),
                ('odendi_mi', models.BooleanField(default=False)),
                ('arac_kodu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.arac')),
                ('personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.personel')),
            ],
        ),
    ]
