# Generated by Django 6.0.3 on 2026-03-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='arac_kodu',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
