# Generated by Django 6.0.3 on 2026-03-18 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_arac_arac_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='arac_durumu',
            field=models.CharField(choices=[('bosta', 'Boşta'), ('musteride', 'Müşteride'), ('rehin', 'Rehin'), ('serviste', 'Serviste')], default='bosta', max_length=20),
        ),
        migrations.AddField(
            model_name='arac',
            name='arac_kimde',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='arac_sinifi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='arac_turu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='cekici_ruhsati_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='egzoz_emisyon_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='ilk_tescil_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='marka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='model_tanim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='model_yili',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='motor_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='muayene_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='mulkiyet_durumu',
            field=models.CharField(choices=[('sirket', 'Şirket Aracı'), ('kiralik', 'Kiralık')], default='sirket', max_length=20),
        ),
        migrations.AddField(
            model_name='arac',
            name='renk',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='arac_resimleri/'),
        ),
        migrations.AddField(
            model_name='arac',
            name='sase_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='segment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='serusefer_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='tescil_sira_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='tescil_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='vites',
            field=models.CharField(blank=True, choices=[('manuel', 'Manuel'), ('otomatik', 'Otomatik'), ('yari_otomatik', 'Yarı Otomatik')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='yakit_tipi',
            field=models.CharField(blank=True, choices=[('benzin', 'Benzin'), ('dizel', 'Dizel'), ('lpg', 'LPG'), ('elektrik', 'Elektrik'), ('hibrit', 'Hibrit')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='ad_soyad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='alis_yeri',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='musteri_adi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='odeme_turu',
            field=models.CharField(choices=[('nakit', 'Nakit'), ('kredi_karti', 'Kredi Kartı'), ('havale', 'Havale/EFT'), ('cari', 'Cari Hesap')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sefer_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_durumu',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('yolda', 'Yolda'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='beklemede', max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_turu',
            field=models.CharField(choices=[('gelis', 'Geliş'), ('donus', 'Dönüş'), ('tahsis', 'Tahsis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='varis_yer_turu',
            field=models.CharField(choices=[('havalimani', 'Havalimanı'), ('gar', 'Gar'), ('kamu', 'Kamu Kurumu'), ('otel', 'Otel'), ('diger', 'Diğer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='varis_yeri',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Bakim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakim_km', models.PositiveIntegerField()),
                ('sonraki_bakim_tarihi', models.DateField(blank=True, null=True)),
                ('sonraki_bakim_km', models.PositiveIntegerField(blank=True, null=True)),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakimlar', to='transfer.arac')),
            ],
        ),
        migrations.CreateModel(
            name='Hasar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya_no', models.CharField(max_length=100)),
                ('hasar_turu', models.CharField(max_length=100)),
                ('hasar_tarihi', models.DateField()),
                ('ekspertiz', models.CharField(blank=True, max_length=200, null=True)),
                ('muafiyet_tutari', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasarlar', to='transfer.arac')),
            ],
        ),
        migrations.CreateModel(
            name='Sigorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_no', models.CharField(max_length=100)),
                ('police_tarihi', models.DateField()),
                ('police_bitis_tarihi', models.DateField()),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigortalar', to='transfer.arac')),
            ],
        ),
    ]
