# Generated by Django 6.0.3 on 2026-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_arac_arac_durumu_arac_arac_kimde_arac_arac_sinifi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='ad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='calisma_turu',
            field=models.CharField(choices=[('tam_zamanli', 'Tam Zamanlı'), ('yari_zamanli', 'Yarı Zamanlı'), ('serbest', 'Freelance/Sözleşmeli')], default='tam_zamanli', max_length=20),
        ),
        migrations.AddField(
            model_name='personel',
            name='gorevi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='is_ayrilis_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='is_baslama_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personel',
            name='soyad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='ad_soyad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
