# Generated by Django 6.0.3 on 2026-03-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_personel_ad_personel_calisma_turu_personel_gorevi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AracTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodu', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tanimi', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='arac',
            name='arac_sinifi',
        ),
        migrations.AddField(
            model_name='arac',
            name='il_kodu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='arac',
            name='arac_turu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.aracturu'),
        ),
    ]
