# Generated by Django 6.0.3 on 2026-03-23 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_aracturu_remove_arac_arac_sinifi_arac_il_kodu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masraf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masraf_turu', models.CharField(choices=[('akaryakit', 'Akaryakıt'), ('lastik', 'Lastik'), ('hgs', 'HGS'), ('ogs', 'OGS'), ('otopark', 'Otopark'), ('bakim', 'Bakım / Servis'), ('yemek', 'Yemek'), ('diger', 'Diğer')], max_length=20)),
                ('tarih', models.DateField(verbose_name='Masraf Tarihi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('para_birimi', models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Dolar ($)'), ('EUR', 'Euro (€)')], default='TRY', max_length=5)),
                ('fis_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fiş / Fatura No')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama / Detay')),
                ('belge', models.FileField(blank=True, null=True, upload_to='masraf_belgeleri/', verbose_name='Fatura/Fiş Belgesi (PDF/Resim)')),
                ('arac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masraflar', to='transfer.arac', verbose_name='İlgili Araç')),
                ('personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masraflar', to='transfer.personel', verbose_name='İlgili Personel')),
            ],
        ),
    ]
