# Generated by Django 6.0.3 on 2026-03-23 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_masraf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Ceza Tarihi')),
                ('saat', models.TimeField(blank=True, null=True, verbose_name='Ceza Saati')),
                ('madde', models.CharField(max_length=200, verbose_name='Ceza Maddesi / İhlal Nedeni (Örn: Radar, Hatalı Park)')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ceza Tutarı (₺)')),
                ('son_odeme_tarihi', models.DateField(blank=True, null=True, verbose_name='İndirimli Son Ödeme Tarihi')),
                ('odendi_mi', models.BooleanField(default=False, verbose_name='Ödendi mi?')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama / Notlar')),
                ('belge', models.FileField(blank=True, null=True, upload_to='ceza_belgeleri/', verbose_name='Ceza Makbuzu / Fotoğrafı')),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cezalar', to='transfer.arac', verbose_name='Ceza Yiyen Araç')),
                ('personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cezalar', to='transfer.personel', verbose_name='Aracı Kullanan Personel')),
            ],
        ),
    ]
