# Generated by Django 6.0.3 on 2026-03-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_ceza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='alis_saati',
            field=models.DateTimeField(verbose_name='Çıkış Saati'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='alis_yeri',
            field=models.CharField(max_length=200, verbose_name='Çıkış Adresi'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='varis_saati',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Varış Saati'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='varis_yer_turu',
            field=models.CharField(choices=[('havalimani', 'Havalimanı'), ('gar', 'Gar'), ('kamu', 'Kamu Kurumu'), ('otel', 'Otel'), ('diger', 'Diğer')], max_length=20, verbose_name='Varış Adresi Türü'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='varis_yeri',
            field=models.CharField(max_length=200, verbose_name='Varış Adresi'),
        ),
    ]
