# Generated by Django 6.0.3 on 2026-03-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_alter_transfer_alis_saati_alter_transfer_alis_yeri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='yolcu_geldi_mi',
            field=models.BooleanField(default=False, verbose_name='Yolcu Geldi mi?'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='yolcu_isim_soyisim',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yolcu İsim Soyisim'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='yolcu_telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Yolcu Telefon Numarası'),
        ),
    ]
