# Generated by Django 6.0.3 on 2026-03-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_transfer_yolcu_geldi_mi_transfer_yolcu_isim_soyisim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='yolcu_isim_soyisim',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='yolcu_telefon',
        ),
    ]
