# Generated by Django 6.0.3 on 2026-04-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0011_firma_alter_arac_il_kodu_arac_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='yolcular',
            field=models.TextField(blank=True, null=True, verbose_name='Yolcu İsim Soyisim ve Numaraları'),
        ),
    ]
