# Generated by Django 6.0.3 on 2026-04-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0012_transfer_yolcular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_durumu',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('basladi', 'Başladı'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='beklemede', max_length=20),
        ),
    ]
