# Generated by Django 6.0.3 on 2026-04-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0013_alter_transfer_transfer_durumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='alis_yeri',
            field=models.TextField(verbose_name='Çıkış Adresi'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='varis_yeri',
            field=models.TextField(verbose_name='Varış Adresi'),
        ),
    ]
