# Generated by Django 6.0.3 on 2026-04-01 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0014_alter_transfer_alis_yeri_alter_transfer_varis_yeri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='yolcular',
        ),
        migrations.CreateModel(
            name='TransferYolcu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', models.CharField(max_length=150, verbose_name='İsim Soyisim')),
                ('telefon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon Numarası')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yolcular_listesi', to='transfer.transfer')),
            ],
        ),
    ]
