# Generated by Django 6.0.3 on 2026-04-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0015_remove_transfer_yolcular_transferyolcu'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferyolcu',
            name='yolcu_turu',
            field=models.CharField(choices=[('yetiskin', 'Yetişkin'), ('cocuk', 'Çocuk'), ('bebek', 'Bebek')], default='yetiskin', max_length=20, verbose_name='Yolcu Türü'),
        ),
    ]
