# Generated by Django 6.0.3 on 2026-04-01 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0016_transferyolcu_yolcu_turu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiralama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teklif_baslangic', models.DateField(blank=True, null=True, verbose_name='Teklif Başlangıç Tarihi')),
                ('teklif_gecerlilik_sonu', models.DateField(blank=True, null=True, verbose_name='Teklif Geçerlilik Sonu')),
                ('baslangic_tarihi', models.DateField(verbose_name='Kiralama Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Kiralama Bitiş Tarihi')),
                ('sure', models.PositiveIntegerField(verbose_name='Süre')),
                ('sure_birimi', models.CharField(choices=[('gun', 'Gün'), ('ay', 'Ay'), ('yil', 'Yıl')], default='gun', max_length=10, verbose_name='Süre Birimi')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat (₺)')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar (₺)')),
                ('sozlesme_imzalandi', models.BooleanField(default=False, verbose_name='Sözleşme İmzalandı mı?')),
                ('teslim_edilen_kisiler', models.CharField(max_length=200, verbose_name='Teslim Edilen Kişi / Kurum')),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiralamalar', to='transfer.arac', verbose_name='Kiralanan Araç')),
            ],
        ),
    ]
