# Generated by Django 6.0.3 on 2026-04-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0017_kiralama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arac',
            name='aktif_mi',
        ),
        migrations.RemoveField(
            model_name='arac',
            name='marka_model',
        ),
    ]
