# Generated by Django 6.0.3 on 2026-04-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0018_remove_arac_aktif_mi_remove_arac_marka_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muhatap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unvan', models.CharField(max_length=100, unique=True, verbose_name='Müşteri Adı / Ünvan')),
                ('vkn', models.CharField(blank=True, max_length=11, null=True, verbose_name='VKN / TCKN')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('aktif', models.BooleanField(default=True, null=True, verbose_name='Aktif mi?')),
            ],
        ),
        migrations.AlterField(
            model_name='arac',
            name='arac_durumu',
            field=models.CharField(choices=[('bosta', 'Faal (Boşta)'), ('musteride', 'Müşteride'), ('rehin', 'Rehin'), ('serviste', 'Serviste')], default='bosta', max_length=20),
        ),
    ]
