# Generated by Django 6.0.3 on 2026-04-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0019_muhatap_alter_arac_arac_durumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiralama',
            name='muhatap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.muhatap', verbose_name='Müşteri (Muhatap)'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='muhatap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.muhatap', verbose_name='Müşteri (Muhatap)'),
        ),
        migrations.AlterField(
            model_name='kiralama',
            name='teslim_edilen_kisiler',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Eski - Teslim Edilen Kişi / Kurum'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='musteri_adi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Eski Müşteri Adı'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='musteri_telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
