# Generated by Django 6.0.3 on 2026-04-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0020_kiralama_muhatap_transfer_muhatap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aracturu',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.firma', verbose_name='Bağlı Olduğu Firma'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_turu',
            field=models.CharField(choices=[('gidis', 'Gidiş'), ('donus', 'Dönüş'), ('gidis_donus', 'Gidiş-Dönüş')], max_length=20),
        ),
        migrations.CreateModel(
            name='MasrafTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanimi', models.CharField(max_length=100)),
                ('firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.firma', verbose_name='Bağlı Olduğu Firma')),
            ],
        ),
        migrations.AlterField(
            model_name='masraf',
            name='masraf_turu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.masrafturu', verbose_name='Masraf Türü'),
        ),
    ]
