# Generated by Django 6.0.3 on 2026-04-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0021_aracturu_firma_alter_transfer_transfer_turu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aracturu',
            name='firma',
        ),
    ]
