# Generated by Django 6.0.3 on 2026-04-06 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0022_remove_aracturu_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='aracturu',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.firma', verbose_name='Bağlı Olduğu Firma'),
        ),
    ]
