# Generated by Django 6.0.3 on 2026-04-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0024_masraf_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='sirket_kodu',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Şirket Kodu'),
        ),
        migrations.AddField(
            model_name='muhatap',
            name='eposta',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta'),
        ),
        migrations.AddField(
            model_name='muhatap',
            name='il',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='muhatap',
            name='ilce',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='muhatap',
            name='musteri_kodu',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Müşteri Kodu'),
        ),
        migrations.AddField(
            model_name='muhatap',
            name='vergi_dairesi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='alis_yer_turu',
            field=models.CharField(blank=True, choices=[('havalimani', 'Havalimanı'), ('gar', 'Gar'), ('kamu', 'Kamu Kurumu'), ('otel', 'Otel'), ('ev', 'Ev'), ('diger', 'Diğer')], max_length=20, null=True, verbose_name='Çıkış Adresi Türü'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='ad',
            field=models.CharField(max_length=200, verbose_name='Şirket Adı'),
        ),
        migrations.AlterField(
            model_name='muhatap',
            name='adres',
            field=models.TextField(blank=True, null=True, verbose_name='Açık Adres'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='varis_yer_turu',
            field=models.CharField(choices=[('havalimani', 'Havalimanı'), ('gar', 'Gar'), ('kamu', 'Kamu Kurumu'), ('otel', 'Otel'), ('ev', 'Ev'), ('diger', 'Diğer')], max_length=20, verbose_name='Varış Adresi Türü'),
        ),
    ]
