# Generated by Django 6.0.3 on 2026-04-07 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0026_alter_muhatap_il'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arac',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.firma', verbose_name='Bağlı Olduğu Şirket'),
        ),
        migrations.AlterField(
            model_name='aracturu',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.firma', verbose_name='Bağlı Olduğu Şirket'),
        ),
        migrations.AlterField(
            model_name='masraf',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.firma', verbose_name='Bağlı Olduğu Şirket'),
        ),
        migrations.AlterField(
            model_name='masrafturu',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.firma', verbose_name='Bağlı Olduğu Şirket'),
        ),
        migrations.AlterField(
            model_name='muhatap',
            name='il',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İl'),
        ),
    ]
