# Generated by Django 6.0.3 on 2026-04-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0027_alter_arac_firma_alter_aracturu_firma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigorta',
            name='sigorta_sirketi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sigorta Şirketi'),
        ),
        migrations.AddField(
            model_name='sigorta',
            name='sigorta_turu',
            field=models.CharField(choices=[('trafik', 'Trafik Sigortası'), ('kasko', 'Kasko'), ('ihtiyari', 'İhtiyari Mali Mesuliyet (İMM)'), ('ferdi_kaza', 'Koltuk Ferdi Kaza')], default='trafik', max_length=50, verbose_name='Sigorta Türü'),
        ),
    ]
