# Generated by Django 6.0.3 on 2026-04-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0028_sigorta_sigorta_sirketi_sigorta_sigorta_turu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='sefer_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Sefer No'),
        ),
    ]
