# Generated by Django 6.0.3 on 2026-04-24 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0030_alter_muhatap_il'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arac',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.firma', verbose_name='Şirket'),
        ),
        migrations.AlterField(
            model_name='aracturu',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.firma', verbose_name='Şirket'),
        ),
        migrations.AlterField(
            model_name='masraf',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.firma', verbose_name='Şirket'),
        ),
        migrations.AlterField(
            model_name='masrafturu',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.firma', verbose_name='Şirket'),
        ),
    ]
