from django.urls import path
from django.contrib.auth.decorators import user_passes_test
from . import views

# Yalnızca personel (admin) olanların erişebilmesi için sarmalayıcı fonksiyon
def staff_only(view_func):
    return user_passes_test(lambda u: u.is_staff, login_url='transfer_listesi')(view_func)

urlpatterns = [
    # Müşteriye ve Personele Açık Olanlar
    path('liste/', views.transfer_listesi, name='transfer_listesi'),
    path('ekle/', views.transfer_ekle, name='transfer_ekle'),
    path('kayit/', views.kayit_ol, name='kayit_ol'),
    path('giris/', views.giris_yap, name='giris_yap'),
    path('cikis/', views.cikis_yap, name='cikis_yap'),
    path('duzenle/<int:id>/', views.transfer_duzenle, name='transfer_duzenle'),
    path('sil/<int:id>/', views.transfer_sil, name='transfer_sil'),
    path('detay/<int:id>/', views.transfer_detay, name='transfer_detay'),
    
    # AJAX Servisleri (Transfer formunda kullanıldığı için açık)
    path('api/arac_detay/<int:id>/', views.get_arac_details, name='get_arac_details'),
    path('api/firma_turleri/', views.get_firma_turleri, name='get_firma_turleri'),
    path('musait-araclar/', views.get_müsait_araclar, name='musait_araclar'),
    path('musait-personeller/', views.get_musait_personeller, name='musait_personeller'),
    path('api/arac-mesgul-tarihler/', views.get_arac_mesgul_tarihler, name='arac_mesgul_tarihler'),
    path('api/personel-mesgul-tarihler/', views.get_personel_mesgul_tarihler, name='personel_mesgul_tarihler'),

    # SADECE PERSONELE (ADMİNE) AÇIK OLANLAR
    path('', staff_only(views.dashboard), name='dashboard'),
    path('talepler/', staff_only(views.transfer_talep_listesi), name='transfer_talep_listesi'),
    path('araclar/', staff_only(views.arac_listesi), name='arac_listesi'),
    path('araclar/ekle/', staff_only(views.arac_ekle), name='arac_ekle'),
    path('araclar/duzenle/<int:id>/', staff_only(views.arac_duzenle), name='arac_duzenle'),
    path('araclar/sil/<int:id>/', staff_only(views.arac_sil), name='arac_sil'),
    path('araclar/detay/<int:id>/', staff_only(views.arac_detay), name='arac_detay'),
    path('personeller/', staff_only(views.personel_listesi), name='personel_listesi'),
    path('personeller/ekle/', staff_only(views.personel_ekle), name='personel_ekle'),
    path('personeller/duzenle/<int:id>/', staff_only(views.personel_duzenle), name='personel_duzenle'),
    path('personeller/sil/<int:id>/', staff_only(views.personel_sil), name='personel_sil'),
    path('masraflar/', staff_only(views.masraf_listesi), name='masraf_listesi'),
    path('masraflar/ekle/', staff_only(views.masraf_ekle), name='masraf_ekle'),
    path('masraflar/duzenle/<int:id>/', staff_only(views.masraf_duzenle), name='masraf_duzenle'),
    path('masraflar/sil/<int:id>/', staff_only(views.masraf_sil), name='masraf_sil'),
    path('masraflar/rapor-belgesi/', staff_only(views.masraf_raporu_belge), name='masraf_raporu_belge'),
    path('cezalar/', staff_only(views.ceza_listesi), name='ceza_listesi'),
    path('cezalar/ekle/', staff_only(views.ceza_ekle), name='ceza_ekle'),
    path('cezalar/duzenle/<int:id>/', staff_only(views.ceza_duzenle), name='ceza_duzenle'),
    path('cezalar/sil/<int:id>/', staff_only(views.ceza_sil), name='ceza_sil'),
    path('cezalar/rapor-belgesi/', staff_only(views.ceza_raporu_belge), name='ceza_raporu_belge'),
    path('kiralamalar/', staff_only(views.kiralama_listesi), name='kiralama_listesi'),
    path('kiralamalar/ekle/', staff_only(views.kiralama_ekle), name='kiralama_ekle'),
    path('kiralamalar/duzenle/<int:id>/', staff_only(views.kiralama_duzenle), name='kiralama_duzenle'),
    path('kiralamalar/sil/<int:id>/', staff_only(views.kiralama_sil), name='kiralama_sil'),
    path('muhataplar/', staff_only(views.muhatap_listesi), name='muhatap_listesi'),
    path('muhataplar/ekle/', staff_only(views.muhatap_ekle), name='muhatap_ekle'),
    path('muhataplar/duzenle/<int:id>/', staff_only(views.muhatap_duzenle), name='muhatap_duzenle'),
    path('muhataplar/sil/<int:id>/', staff_only(views.muhatap_sil), name='muhatap_sil'),
    path('firmalar/', staff_only(views.firma_listesi), name='firma_listesi'),
    path('firmalar/ekle/', staff_only(views.firma_ekle), name='firma_ekle'),
    path('firmalar/duzenle/<int:id>/', staff_only(views.firma_duzenle), name='firma_duzenle'),
    path('firmalar/sil/<int:id>/', staff_only(views.firma_sil), name='firma_sil'),
    path('arac-turleri/', staff_only(views.arac_turu_listesi), name='arac_turu_listesi'),
    path('arac-turleri/ekle/', staff_only(views.arac_turu_ekle), name='arac_turu_ekle'),
    path('arac-turleri/duzenle/<int:id>/', staff_only(views.arac_turu_duzenle), name='arac_turu_duzenle'),
    path('arac-turleri/sil/<int:id>/', staff_only(views.arac_turu_sil), name='arac_turu_sil'),
    path('masraf-turleri/', staff_only(views.masraf_turu_listesi), name='masraf_turu_listesi'),
    path('masraf-turleri/ekle/', staff_only(views.masraf_turu_ekle), name='masraf_turu_ekle'),
    path('masraf-turleri/duzenle/<int:id>/', staff_only(views.masraf_turu_duzenle), name='masraf_turu_duzenle'),
    path('masraf-turleri/sil/<int:id>/', staff_only(views.masraf_turu_sil), name='masraf_turu_sil'),
    path('sefer-listesi/', staff_only(views.sefer_listesi), name='sefer_listesi'),
    path('seferler/rapor/<int:personel_id>/', staff_only(views.sefer_raporu_belge), name='sefer_raporu_belge'),
    path('transfer/durum-guncelle/<int:id>/<str:yeni_durum>/', staff_only(views.transfer_durum_guncelle), name='transfer_durum_guncelle'),
    path('sigortalar/', staff_only(views.sigorta_listesi), name='sigorta_listesi'),
    path('sigortalar/ekle/', staff_only(views.sigorta_ekle), name='sigorta_ekle'),
    path('sigortalar/<int:id>/duzenle/', staff_only(views.sigorta_duzenle), name='sigorta_duzenle'),
    path('sigortalar/<int:id>/sil/', staff_only(views.sigorta_sil), name='sigorta_sil'),
    path('raporlar/', staff_only(views.raporlar_ana), name='raporlar_ana'),
    path('raporlar/arac/', staff_only(views.arac_raporu), name='arac_raporu'), 
    path('raporlar/transfer/', staff_only(views.transfer_raporu), name='transfer_raporu'), 
    path('raporlar/masraf/', staff_only(views.masraf_raporu), name='masraf_raporu'), 
    path('raporlar/ceza/', staff_only(views.ceza_raporu), name='ceza_raporu'),
    path('raporlar/kiralama/', staff_only(views.kiralama_raporu), name='kiralama_raporu'), 
    path('raporlar/hatirlatma/', staff_only(views.hatirlatma_raporu), name='hatirlatma_raporu'),
]